# Methods {#methodology}

To begin the process of evaluating the effect of wheelchair use on travel
behavior, we have developed a two-stage methodology. First, we
estimate a daily activity pattern choice model using data from the 2017 NHTS. We
then apply the coefficients obtained from that model in an activity-based model
representing the Wasatch Front Region in Utah.

Activity-based models are a relatively mature construct in travel behavior
research and in practical demand forecasting [@rasouli2014activity]. Activity-based models attempt
to recreate the long- and short-term decision patterns of synthetic individuals using a
chain of econometric and statistical choice models. The specific sub-models included
in this chain can vary between specific implementations, but a recent 
open-source project --- ActivitySim [@activitysim] --- implements a popular 
set of models developed by @davidson2010ct. Specifically, the ActivitySim demonstration
model is a implementation of the "Travel Model One" model for the Metropolitan
Transportation Commission (MTC, San Francisco Bay) [@erhardt2012mtc].
For simplicity and potential future comparison with other models, we apply the
ActivitySim model in this research.

## Choice Model
The first step in the ActivitySim model chain is a \emph{daily activity pattern}
model of the type described by @Bradley2005. This model 
allows individuals to choose one of three daily activity patterns:

  - Mandatory ($M$) daily patterns revolve around school and work activities that
  are typically considered non-discretionary. These activities and the travel
  to them anchor an individual's daily schedule, though other tours are possible.
  - Non-Mandatory ($NM$) daily patterns involve only discretionary activities: 
  shopping, maintenance, etc.
  - At-Home ($H$) daily patterns describe the schedule and activities of 
  individuals who never leave the home during the travel day.
  
The choice between the daily patterns is described with a multinomial logit
model [@Domencich1975], where the utility functions for each option are
determined by an individual's socioeconomic characteristics and person type
segment. The specific innovation of the @Bradley2005 model is that the daily
activity patterns are coordinated, or that the choice of one individual in a
household influences the choice probability of other household members. 

Data for this study comes from the 2017 NHTS [@fhwa2017], which includes
responses from across the United States involving rural, urban, and suburban
areas. We restrict the data to households residing in an metropolitan statistical
area (MSA) between one and three million in population. There are
76,367 individuals in 36,497 households that responded to the NHTS from these
areas, though not all of these records are useful due to missing or incomplete
data in key variables.

The NHTS releases public data in separate tables for persons, households,
trips and vehicles; to determine the daily activity pattern for a given
individual it was necessary to transform the trips table into a table of
activities. We did this by reconstructing a schedule for each person from the
reported trip origin and destination activity codes. We then determined whether
each reported tour (a chain of activities away from the individual's home)
contained a mandatory school or work activity. If any tour contained a mandatory
activity, the person's entire daily activity pattern was classified as "mandatory";
if not, the daily activity pattern was "non-mandatory." By identifying respondents
in the persons table without records in the trips table, we can determine
individuals with a "home" daily activity pattern.

The NHTS has a number of questions where respondents can indicate a disability
for themselves or other household members. Each respondent is asked "Do you
have a condition or handicap that makes it difficult to travel outside of the
home?" If the answer is yes, several follow-up questions are asked, including
"Do you use any of the following medical devices? Select all that apply." The
list of medical devices respondents can indicate includes canes, walkers,
seeing-eye dogs, crutches, motorized scooters, manual wheelchairs, 
motorized wheelchairs, or something else (other). 
For this study, we identify wheelchair users as respondents who report using a
manual wheelchair, mechanical wheelchair, or motorized scooter.


The specific variables included in the daily activity pattern choice models
are based initially on the variables used in MTC Travel Model One [@erhardt2012mtc].
The variables available in the NHTS include the age of
the person and the household income treated as categorical ranges; gender, work,
and college degree status are treated as binary values. Automobile availability is
included via a binary "sufficiency" variable where a household with at least as
many vehicles as adults is considered "auto sufficient." Descriptive statistics
of the model variables are given in  Table \@ref(tab:descriptive-stats).

```{r descriptive-stats}
tar_load(descriptives)
datasummary_balance(~Type, data = descriptives, dinm = FALSE, 
                    title = "Model Estimation Data: Descriptive Statistics") %>%
  kable_styling(latex_options = "scale_down") %>%
  landscape()
```

We adopt the person type segmentation strategy employed by ActivitySim;
segmentation allows for heterogeneity in available alternatives and utility
coefficients between individuals with highly divergent expected behaviors. For
example, full time workers and pre-driving age school children will have
strongly different responses to income, automobile availability, and other
variables in determining their most likely daily pattern. 
ActivitySim classifies persons into seven person segments, though we only
consider four types in this study, defined as follows:

   - Full-time workers (FW) - reported working "full-time" at their primary job.
   - Part-time worker (PW) - reported working "part-time" at their primary job,
   as well as any person who reported being a "non-worker" or "retired" who nevertheless
   reported a work or school activity.
   - Non-working adults (NW) - reported "unemployed" as their primary activity
 of the previous week, as well as individuals over 18 who were not classified
 elsewhere.
 - Retired (RT) - reported "retired" as their primary activity of the previous
 week, or who are over the age of 65 and reported that they were not workers.
 
The other three person types are university students, schoolchildren under
driving age, and driving-age schoolchildren. A limited number of individuals who
could plausibly be considered university students responded to the NHTS, so we
cannot estimate reliable choice models. Among schoolchildren of any age, too few
report using wheelchairs to justify including these segments in this study.


## ActivitySim Implementation

After obtaining an estimate for the relationship between wheelchair use and
daily activity patterns, we wish to understand the impact of this variable on
overall transportation demand forecasting. To do this, we can place the
enhanced daily activity pattern model including this relationship within an  
Activitysim implementation. In this case, we use an implementation of ActivitySim
in the Wasatch Front region of Utah; this implementation includes the Salt Lake
City, Provo, and Ogden metropolitan areas.^[This implementation is not the 
official regional travel demand model; the calibration and development of this
model is described in @udotwheelchairs.]

The synthetic population for this implementation is generated with PopulationSim
[@paul2018], which uses American Community Survey Public Use Microdata Sample
(ACS PUMS)[@acspums] as seed table. Any variables from ACS PUMS can in principle 
be included in synthetic population and therefore in the model. The ACS PUMS
includes a “disability” variable but not specific information on wheelchair use.
The NHTS, however, does explicitly contain a wheelchair use variable as
described earlier.

Using the NHTS data, we estimated a binary logit regression model where the
probability for wheelchair use was determined to be a function of age,
\begin{equation}
  P_{\mathrm{wheelchair | disability}}=-2.59 + 0.014*\mathrm{age}
  (\#eq:wheelchair)
\end{equation}
Other specifications of this regression equation did not result in substantively
different model fit. For each person in the synthetic population with a disability
as sampled from the ACS PUMS seed table, we determined the probability they
would use a wheelchair based on the model in Equation \@ref(eq:wheelchair). A random
draw allocated these individuals into using or not using a wheelchair.
Of the total synthetic population, those using a wheelchair consisted of 0.8
percent of all individuals.

With the synthetic population described above, we modified the ActivitySim 
daily activity pattern model to consider wheelchair use. We then compared two 
complete runs of ActivitySim on the same synthetic population of 2.47 million
individuals, with and without the wheelchair use variable activated. As described
earlier, the daily activity pattern model in ActivitySim is coordinated, meaning
that when an individual has an increased likelihood of choosing an at-home tour,
other members of the household will have an increased likelihood as well [@Bradley2005].
Thus it is important to evaluate not only the daily activity patterns of 
individuals who use wheelchairs, but also their household members.



























