# Discussion {#discussion}

Disability status is almost never included in travel demand forecasting 
efforts for a number of reasons. First is a practical issue; each element
of a population included in a model requires additional effort to not only catalog
and calibrate in the base year, it requires forecasting that variable out into 
the future planning years. Limiting the variables considered to the typical set 
of age, employment status, household size, and income (among potentially a few
others) reduces burden on planners and simplifies the data management pipeline.
Second, the variety of possible travel-limiting disabilities and the perceived
small size of the affected population might make understanding the travel 
behavior impacts of all potential disabilities a high-cost, low-impact proposal
in the large scheme of a travel model.

There is an important philosophical argument to be had about the equity
implications of considering disability within travel forecasting efforts. On
one hand, excluding disability from travel behavior models might reinforce the
"invisibility" of this population when developing transportation plans and other
public policies. If a population is not modeled, it is difficult to evaluate how
various policies would impact them within a model.  Thus household income is left
as virtually the only equity consideration in travel forecasts [@bills2012].
On the other hand, current
travel modeling practice assumes constant behavioral impacts into the future. Is 
is correct or fair to assume that the travel costs and obstacles currently
faced by individuals with disabilities will continue unabated twenty or thirty
years from now?  Many of these same philosophical questions also apply to 
other variables that might be observed to affect travel behavior, such as race 
or ethnic group or religious affiliation [e.g., @vyas2015]. 

This study suggests that omitting wheelchair use is not without cost.
The impact of wheelchair use on individual travel behavior appears to be
substantial, and is potentially of a scale to affect travel forecasting results
in particular areas. Further research is required, but it is possible that wheelchair
use could result in different outcomes for transit ridership and local trip
production at least. The daily activity pattern model presented in this research
is only the first step in a typical travel activity modeling process. Future
research should undertake a rigorous evaluation of the effect of wheelchair use
on vehicle ownership, tour frequency, activity location choice, and travel mode.
It is possible that other disabilities will need to be investigated as well.

The NHTS provides a sufficiently large sample of individuals who use wheelchairs
to undertake the analysis presented here. It is unlikely, however, to be useful
for some of the other travel activity models just described. Activity location
choice models require substantially more precise geographic detail --- including
detail on non-chosen alternative locations --- than is provided in the NHTS.
Local household travel surveys are unlikely to sample enough individuals who use
wheelchairs to estimate robust effects without targeted oversampling techniques. 
The results of this study raise a question as to whether planning agencies 
ought to consider conducting this oversampling to enable future research. 

The model specifications  presented in Table \@ref(tab:model-coef) each consider 
wheelchair use independently from other variables. It is likely however, that there
could be some interaction effects among the various individual attributes. 
To wit: do wheelchair users who hold bachelor's degrees behave differently
with respect to activity pattern than wheelchair users with less education?

This study used information from all United States metro areas between one and
three million in population. It is possible that the obstacles wheelchair users
face in some of these metro areas  are larger or smaller than others. It is also
possible that larger or smaller metro areas would present different challenges
or provide different resources to wheelchair users. The same logic extends to other
countries besides the United States. Examining the role of wheelchair use on daily
activity pattern in other national contexts is important, as would be further 
research on other categories of disability.



