# Conclusion {#conclusion}

In the generation since the enactment of the ADA in 1990, much progress has
been made in the United States in making public accommodations and transportation
services available to all users regardless of their disability status. 
Despite this progress, the results of this research suggest that wheelchair
users still face substantial friction in their daily travel after controlling
for age, income, and other common sociodemographic characteristics. Though
the size of the wheelchair-using population is relatively small --- particularly
within the context of a regional travel demand model --- it may be spatially
concentrated to the point where it could influence forecasts for individual transit
services or local highway facilities.

As transportation planners are being asked to consider equity in more policies
and contexts, the needs of wheelchair users and others with travel-limiting
disabilities should be considered in more contexts. The exclusion of wheelchair
users from travel models means that services and policies aimed at assisting
this community may be devalued relative to highway capacity and other more
traditional projects. The consequences of this exclusion should be investigated,
as well as the exclusion of other variables that would enable a more holistic
assessment of winners and losers in the transportation system.

