---
title: "How far are we from transportation equity? Measuring the effect of wheelchair use on daily activity patterns."
author:
  - name: Gregory S. Macfarlane
    email: gregmacfarlane@byu.edu
    affiliation: BYU
    footnote: 1
  - name: Nate Lant
    email: natelant@gmail.com
    affiliation: BYU
address:
  - code: BYU
    address: Brigham Young University, Civil and Construction Engineering Department, 430 Engineering Building, Provo, Utah 84602
footnote:
  - code: 1
    text: "Corresponding Author"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "the 12$^{th}$ International Scientific Conference on Mobility and Transport"
bibliography: [book.bib]
csl: elsevier-harvard-italics.csl
always_allow_html: true
link-citations: yes
abstract: |
  The mobility needs of individuals with travel-limiting disabilities has been a transportation policy priority in the United States for more than thirty years, but efforts to model the behavioral implications of disability on travel have been limited. In this research, we present a daily activity pattern choice model for multiple trip purposes including an individual’s wheelchair use as an explanatory variable. The model results show a strong negative impact of wheelchair use on tour making, exceeding the impact of other variables commonly considered in such models. We then apply the estimated model within an activity-based model for the Wasatch Front region in Utah; the results suggest a shift in tour making of sufficient scale — among both wheelchair users and those in their households — to warrant further scrutiny and analysis.

keywords: Transportation equity; travel behavior
description: "Coordinated daily activity patterns of wheelchair users."
layout: "3p, authoryear, review"
header-includes:
  - \usepackage{booktabs}
  - \usepackage{siunitx}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage[utf8]{inputenc}
  - \usepackage{makecell}
  - \usepackage{xcolor}
---

# Introduction {#intro}

```{r setup, include = FALSE}
# load R libraries here; the `include` flag in the chunk options above tells
# whether to print the results or not. Usually you don't want to print the
# library statements, or any code on the pdf.
# Main Packages ========
# I use these in every doc
library(tidyverse)
library(knitr)
library(kableExtra)
library(modelsummary)
library(targets)
options(dplyr.summarise.inform = FALSE)
# Other packages ------
# These sometimes get used, and sometimes don't.
library(mlogit)

# Instructions and options =========
# prints missing data in tables as blank space
options(knitr.kable.NA = '') 
# tells kableExtra to not load latex table packages in the chunk output
options(kableExtra.latex.load_packages = FALSE) 
# round and format numbers that get printed in the text of the article.
inline_hook <- function(x) {
  if (is.numeric(x)) {
    format(x, digits = 3, big.mark = ",")
  } else x
}
knitr::knit_hooks$set(inline = inline_hook)
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
# options for latex-only output
if(knitr::is_latex_output()) {
  knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
} 

knitr::write_bib(c(.packages(), "bookdown"), "packages.bib")
```



In 1990, the United States Congress passed the Americans with Disabilities Act (ADA), 
seeking to protect individuals with qualifying disabilities from discrimination
while using public services including transportation systems (Title II), in
public accommodations (Title III), and various other specific situation. For
transportation service providers, ensuring equal access for wheelchair users is
a critical design constraint for vehicles as well as stations and the surrounding areas
[@fhwaada].
Buses and trains had to be redesigned with low floors and access ramps;
elevators and ramps needed to be installed in stations alongside escalators and
stairs. Even today, most traditional automobiles remain inaccessible to wheelchair users --- at least
without substantial modification. This last challenge is
a particular concern for emerging mobility providers --- who often use
private vehicles owned by individual operators --- and for public transit agencies who 
are beginning to cooperate with such providers to operate first/last mile 
services [@Shaheen2016;@Macfarlane2021].


Though the ADA only requires agencies to provide reasonable accommodation on 
public conveyances and does not try to establish equity in outcomes, the passage
of 30 years provides a convenient time to consider what gaps and challenges
persist for wheelchair users in accessing and using the transportation system.
Specifically, what gap exists in the observed travel behavior outcomes of
wheelchair users *vis a vis* the non wheelchair using population, all else equal?
And more importantly, how should this gap be applied within travel forecasting
models and related planning activities?

In this paper, we investigate the degree to which daily activity patterns are
influenced by an individual's use of a wheelchair. This involves two separate
analyses: first, we model daily activity pattern choice using responses to the
2017 National Household Travel Survey [@fhwa2017], incorporating the individual's
wheelchair use as an explanatory variable. Second, we apply the behavioral
estimates obtained from the choice analysis in a modified activity-based model
for the Wasatch Front metropolitan region in Utah to estimate the
population-level effects of introducing wheelchair status in a regional travel
demand model.

The paper proceeds in a typical fashion. A [literature review](#literature)
discusses prior attempts to evaluated and quantify the travel behavior of
users with disabilities. A section [describing the methodology](#methodology)
of the choice analysis and model application is followed by [a discussion of the results](#results)
from both analyses. The paper concludes with [a discussion](#discussion)
of limitations in this analysis and associated avenues for future research and
policy intervention.




